### ISSUE TITLE
[BUG] Instructions in docs to install from package manager results in package not found

### ISSUE THREAD

**Issue by wbnns** [esa/cascade#37]
**Describe the bug**
In the `Installation` section of the docs, after adding `conda-forge`, the `cascade` package cannot be found.

**To Reproduce**
1. Go to [docs](https://esa.github.io/cascade/install.html#installing-from-a-package-manager)
2. Follow instructions to use Conda to install from package manager
3. Encounter `PackagesNotFoundError`

**Expected behavior**
The cascade package should be able to be installed by following the aforementioned steps in the documentation.

**Screenshots**
```
(cascade_devel) [cascade] conda install cascade                                                
Collecting package metadata (current_repodata.json): done                                                
Solving environment: failed with initial frozen solve. Retrying with flexible solve.                     
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cascade

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Environment (please complete the following information):**
 - OS: Fedora 37
 - Installation method: conda
 - Version: 0.1

**Comment by darioizzo** [comment]
Indeed, cascade is currently unreleased and no conda packages have been built yet. This whole repository is under construction. We made it public rather than private early on as we has scheduled release in January ... but we are a few weeks late ....

**Comment by wbnns** [comment]
Hi @darioizzo! Ah, ok, understood and thanks for the insight.

**Comment by bluescarni** [comment]
@wbnns The installation instructions should now be up to date:

https://esa.github.io/cascade/install.html

We currently have packages for conda and pip.

Closing the issue, please re-open if needed.

**Comment by wbnns** [comment]
@bluescarni Cheers! Thanks!!
